### ISSUE TITLE
请问你是需要制作tg小游戏吗？这个我是可以做到的。

### ISSUE THREAD

**Issue by yt123hhhh** [Hu-Wentao/Hu-Wentao#1]
https://github.com/GFMiner/miner_base/blob/main/examples/example4_tg_yescoin.py
这样的脚本多少钱？
YesCoin是一个Tg小游戏,实际上是一个h5网页.
脚本的功能是通过直接发送相关按钮的API请求,来替代手动操作.
上面脚本示例中,Tg登陆相关的代码都不用写, 只要需要写通过api请求模拟网页操作.
演示的是YesCoin, 需要大约50个类似的项目脚本.

我是在接单群看见的，但是走接单群会有收中介费，所以我们可以试试绕过中介，如果是真的可以联系我，如果不是我可以删除掉该帖子

**Comment by Hu-Wentao** [comment]
GFMiner项目面向开发者集成多种插件，降低脚本开发门槛。
面向终端用户，提供资源管理服务，任何人都可以开发自定义脚本使用。
